### ISSUE TITLE
compilation problems

### ISSUE THREAD

**Issue by chunzhi666** [NVlabs/ParallelInversion#2]
Hi, thank you so much for the impressive work and sharing the codes!
I have tried the installation steps according to the instructions, but I encountered some problems and I sincerely hope to get your advice on them. 
First, when I use 'git clone --recursive' command, it fails to clone the submodules into 'dependencies', for example 'glfw'. But it's ok to clone all the submodules when I use the instant-ngp repo. I am not quite sure what has caused this problem.
Second, after I solved the first issue by git clone every required submodule into 'dependencies', I failed to compile when running 'cmake --build build --config RelWithDebInfo -j'. I have checked that most error is about missing or undefined objects in 'testbed.cu' and some other source files, which I suppose may be related to the cmake process. Could you please give me some suggestions on solving the issue?

**Comment by Uio96** [comment]
Thanks for sharing the details. Could you also share the specifications of your system? I only tested on Ubuntu 20.04 before while it may have some compatibility issues in other settings.

By the way, this repo is built on an old version of Instant-ngp so its latest setting may not apply to this repo.

**Comment by chunzhi666** [comment]
Thank you for the response. Would you mind checking if the version numbers are available for submodules in 'dependencies' folder? Currently I cannot see some of the submodules in 'dependencies', and I think I might have used the incompatible code versions. Thanks a lot for your help!

**Comment by Uio96** [comment]
> Thank you for the response. Would you mind checking if the version numbers are available for submodules in 'dependencies' folder? Currently I cannot see some of the submodules in 'dependencies', and I think I might have used the incompatible code versions. Thanks a lot for your help!

Thanks for sharing the issue. I have tried to fix the problem in the latest commit. Could you try again?

**Comment by chunzhi666** [comment]
> > Thank you for the response. Would you mind checking if the version numbers are available for submodules in 'dependencies' folder? Currently I cannot see some of the submodules in 'dependencies', and I think I might have used the incompatible code versions. Thanks a lot for your help!
> 
> Thanks for sharing the issue. I have tried to fix the problem in the latest commit. Could you try again?

The compilation is OK now. Many thanks to your kind help!
